export enum CommandCode {
  SENDER_DEVICE_INFO = 0x0000,
  SENDER_PAIR = 0x0001,
  SENDER_DPS = 0x0002,
  SENDER_DEVICE_STATUS = 0x0003,
  SENDER_UNBIND = 0x0005,
  RECEIVE_DP = 0x8001,
  RECEIVE_TIME_DP = 0x8003,
  RECEIVE_SIGN_DP = 0x8004,
  RECEIVE_SIGN_TIME_DP = 0x8005,
  RECEIVE_TIME1_REQ = 0x8011,
  RECEIVE_TIME2_REQ = 0x8012,
}

export enum SecurityFlag {
  AUTH = 0x01,
  LOGIN = 0x04,
  SESSION = 0x05,
}

export enum DpType {
  RAW = 0,
  BOOL = 1,
  VALUE = 2,
  STRING = 3,
  ENUM = 4,
  BITMAP = 5,
}

export enum AuthState {
  DISCONNECTED = 'DISCONNECTED',
  CONNECTING = 'CONNECTING',
  AUTH_DEVICE_INFO = 'AUTH_DEVICE_INFO',
  AUTH_PAIR = 'AUTH_PAIR',
  AUTH_STATUS = 'AUTH_STATUS',
  READY = 'READY',
  ERROR = 'ERROR',
}
